version: '1.0'

services:
  db:
    image: postgres:15-alpine
    container_name: xenoplanner-compose-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    networks:
      - default

  backend:
    build: .
    container_name: xenoplanner-backend
    depends_on:
      - db
    networks:
      - default